name: ml-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.7
  - joblib==1.5.0
  - keras==3.10.0
  - matplotlib==3.9.2
  - numpy==1.26.4
  - pandas==2.2.2
  - seaborn==0.13.2
  - scikit-learn==1.6.1
  - tensorflow==2.19.0
  - scikeras==0.11.0
  - tf-keras-vis==0.8.1
